# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Brackets
# Repository: https://github.com/arcticicestudio/nord-brackets
# License:    MIT
# References
#   https://docs.travis-ci.com

language: node_js
sudo: false
dist: trusty
os:
  - linux
  - osx
node_js:
  - "6"
  - "7"
before_install:
  - rm -rf ./node_modules
before_script:
  - npm install -g gulp-cli
  - npm install gulp
  - npm install
script:
  - gulp --harmony lint
